// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3pdXG2WnAYP_YrBHa2iT6ude2rYNHJo',
    appId: '1:739891537177:web:a09918fbff139a71d2d188',
    messagingSenderId: '739891537177',
    projectId: 'gym-trackr-88f3b',
    authDomain: 'gym-trackr-88f3b.firebaseapp.com',
    storageBucket: 'gym-trackr-88f3b.appspot.com',
    measurementId: 'G-F2TYPXBLM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKASZTaWm2THbDQ09RL_pGdKbX32WPerI',
    appId: '1:739891537177:android:646346b384f1af07d2d188',
    messagingSenderId: '739891537177',
    projectId: 'gym-trackr-88f3b',
    storageBucket: 'gym-trackr-88f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCURfJj8QSagP5PUwOBuAGkkx9D2EFTs',
    appId: '1:739891537177:ios:061101e1ae288ffad2d188',
    messagingSenderId: '739891537177',
    projectId: 'gym-trackr-88f3b',
    storageBucket: 'gym-trackr-88f3b.appspot.com',
    iosBundleId: 'com.example.gymtrackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMCURfJj8QSagP5PUwOBuAGkkx9D2EFTs',
    appId: '1:739891537177:ios:061101e1ae288ffad2d188',
    messagingSenderId: '739891537177',
    projectId: 'gym-trackr-88f3b',
    storageBucket: 'gym-trackr-88f3b.appspot.com',
    iosBundleId: 'com.example.gymtrackr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM3pdXG2WnAYP_YrBHa2iT6ude2rYNHJo',
    appId: '1:739891537177:web:bbd4f5f138a90cebd2d188',
    messagingSenderId: '739891537177',
    projectId: 'gym-trackr-88f3b',
    authDomain: 'gym-trackr-88f3b.firebaseapp.com',
    storageBucket: 'gym-trackr-88f3b.appspot.com',
    measurementId: 'G-JMPGQF1KBK',
  );
}
